# HideAndCustomPlugins by the Austrian Developer LauseggerDevelopment (lausi1793)
# Type here your Custom Plugins in the config.yml
HideAndCustomPlugins:
  plugins: Here, is, nothing, to, see
  hideversion: 'I dont think soo ...'
