# HideAndCustomPlugins by the Austrian Developer LauseggerDevelopment (lausi1793)
# Type here your Custom Plugins in the config.yml
HideAndCustomPlugins:
  updateNotification: true
  disableHelpCommand: false
  plugins: Here, is, nothing, to, see
  AccessDenied: 'I dont think soo ...'
