name: HideAndCustomPlugins
main: at.mcnetwork.lausi.HideAndCustomPlugins
depend: [ProtocolLib]
version: 1.3.5
author: LauseggerDevelopment
website: http://McNetwork.at
commands:
  hcp:
    usage: /hcp
    description: Information about the plugin.

permissions:
  hideandcustomplugins.*:
    description: Only OP
    children:
      hideandcustomplugins.bypass: true
      hideandcustomplugins.reload: true
    default: op
  hideandcustomplugins.reload:
    description: Reload of the config.yml.
  hideandcustomplugins.bypass:
    description: Bypasses the plugin
