name: HideAndCustomPlugins
main: at.mcnetwork.lausi.HideAndCustomPlugins
depend: [ProtocolLib]
version: 1.3
author: LauseggerDevelopment
website: http://McNetwork.at
commands:
  hideandcustomplugins:
    usage: /hcp
    description: Small Overview of the commands.
  hcpreload:
    usage: /hcpreload
    description: Reload of the config.yml.

permissions:
  hideandcustomplugins.*:
    description: Only OP
    children:
      hideandcustomplugins.bypass: true
      hideandcustomplugins.reload: true
    default: op
  hideandcustomplugins.reload:
    description: Reload of the config.yml.
